from data_structures.classification_labels.multi_label_data import MultiLabelData
from data_structures.multi_task_data_sample import MultiTaskDataSample
from data_structures.points.keypoints import Keypoints
from data_structures.points.lane_lines_keypoints import LaneLinesKeypoints